ssh:
  user: travis
  # either "password" or "key"
  auth_type: key
  # file path to your SSH key. only necessary if auth_type is "key"
  key_path: ~/.ssh/id_rsa_gc

nodes:
  - {name: core-db5-staging, host: core-db5-staging.gamechanger.io}
  - {name: core-db6-staging, host: core-db6-staging.gamechanger.io}

collectors:
  - {name: MongoTop, type: MongoTop, port: 27018, path: /opt/mongodb/bin/mongotop}
  - {name: MongoStat, type: MongoStat, port: 27018, path: /opt/mongodb/bin/mongostat}
